### ISSUE TITLE
Navigation in what sense this library is used

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [tyczj/MapNavigator#17]
I want to know one kind of navigation is just making path between two points and second is while you are traveling in car along the path it will guide you your current location on path with right and left directions. So i want to ask what are the capabilities of this library regarding both scenarios?

**Comment by tyczj** [comment]
all this library does it plot a path from one point to another. real time routing is against google's TOS. You can use this library to aid in providing turn-by-turn directions but you do it at your own risk
