### ISSUE TITLE
hide or remove a route polyline when another is called

### ISSUE THREAD

**Issue by albersmc** [tyczj/MapNavigator#18]
Hi, thanks for this library that works perfect. I have a question and i hope you can get me into the right way.

I draw a route from two point (fixed), and clicking in the infoview the route (polyline) will drawn into the map and it works. By the way i have 20 different marker, and i want to draw a route only when click on the infoview. I mean, if there is already a route in the map, clicking in one other infoview, this route have to be removed and the new one has to be added in the map.

I have a Switch-case method to call each route by clicking in the infoview of the marker, this is a snippet of my code:

 switch (markerIndex){
                    case 0:

```
                    start = new LatLng(22.28861858, 11.32771726);
                    end = new LatLng(22.48861858, 11.36779726);

                    Routing routing = new Routing(Routing.TravelMode.WALKING);
                    routing.registerListener(ActivityOutdoor.this);
                    routing.execute(start, end);

                    break;
                case 1:
                    start = new LatLng(21.48861858, 11.32771726);
                    end = new LatLng(23.48861858, 13.36779726);

                    Routing routing1 = new Routing(Routing.TravelMode.WALKING);
                    routing1.registerListener(ActivityOutdoor.this);
                    routing1.execute(start, end);
                    break;

                default:
                    break;


            }
```

Do you know how to remove the previous route, when click the other infoview?
I used map.clear(); but it will delete all the content of the map
Thanks in advance
Brus

**Comment by sbelloz** [comment]
If you have a list of Polyline you can cycle on it and remove every polyline doing polyline.remove() 

use method In `Navigator` to obtain list of polylines:

```
getPathLines()
```

then:

```
   public void clearPathLines() {
        if (lines != null && !lines.isEmpty()) {
                for (Polyline polyline : lines) {
                    polyline.remove();
                }
            lines.clear();
        }
    }
```

**Comment by albersmc** [comment]
Hi, thanks for the reply. I don't have a list of polyline, i add the route for each click in the infoview in  the switch-case:
case 1:
                    start = new LatLng(21.48861858, 11.32771726);
                    end = new LatLng(23.48861858, 13.36779726);

```
                Routing routing1 = new Routing(Routing.TravelMode.WALKING);
                routing1.registerListener(ActivityOutdoor.this);
                routing1.execute(start, end);
                break;
```

for each marker i edit start, end and rename routing.  In the case-break if i call map.clear(), it will remove all the marker-polylne ecc, but i want to remove only the previous route. Do you know how to do that?

**Comment by tyczj** [comment]
you get the lines by calling `getPathLines()` from your `Navigator` object
